version: 2.1
jobs:
  security_test:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Install tfsec
          command: |
            curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - checkout
      - run:
          name: Use tfsec to test Terraform for vulnerabilities
          command: |
            tfsec ./infrastructure/ -m CRITICAL
  terratest-job:
    docker:
      - image: cimg/go:1.22
    steps:
      - run:
          name: Install terragrunt and terraform
          command: |
            if [[ $(uname -m) == x86_64 ]]; then export ARCHITECTURE=amd64; else export ARCHITECTURE=arm64; fi
            wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.9/terragrunt_linux_$ARCHITECTURE
            chmod u+x terragrunt
            mv terragrunt /home/circleci/bin/terragrunt
            wget -O terraform.zip https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_$ARCHITECTURE.zip
            unzip terraform.zip
            ls -l
            chmod u+x terraform/terraform
            mv terraform/terraform /home/circleci/bin/terraform
            terraform -version
            terragrunt -v
      - checkout
      - run:
          name: Configure test dependencies and run tests
          command: |
            cd ./terratest/test/
            go mod init infra_test
            go mod tidy
            go test -v -timeout 30m
            

workflows:
  test-workflow:
    jobs:
      - security_test
      - terratest-job:
          requires:
            - security_test