apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-app
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: tf-app
  path: ./kubernetes/fluxcd/repositories/infra-repo/apps/tf-app
  prune: true
  wait: true
  timeout: 5m0s
